USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'MovingCompanies')
DROP DATABASE MovingCompanies;
GO

CREATE Database [MovingCompanies]
go

USE [MovingCompanies]
go

DROP TABLE IF EXISTS [CREW_ASSIGN];
DROP TABLE IF EXISTS [VEHICLE_ASSIGN];
DROP TABLE IF EXISTS [MATERIAL_USAGE];
DROP TABLE IF EXISTS [INVENTORY_ITEM];
DROP TABLE IF EXISTS [INVOICE];
DROP TABLE IF EXISTS [ESTIMATE];
DROP TABLE IF EXISTS [ORDER];
DROP TABLE IF EXISTS [LOCATION];
DROP TABLE IF EXISTS [GEOGRAPHIC_ZONE];
DROP TABLE IF EXISTS [PACKING_MATERIAL];
DROP TABLE IF EXISTS [CREW_MEMBER];
DROP TABLE IF EXISTS [VEHICLE];
DROP TABLE IF EXISTS [CONSULTANT];
DROP TABLE IF EXISTS [CUSTOMER];
GO

CREATE TABLE CUSTOMER (
CustomerID INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
Phone VARCHAR(20) NOT NULL,
Email VARCHAR(200) NOT NULL);

CREATE TABLE CONSULTANT (
ConsultantID INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
ConsultantType VARCHAR(50) NOT NULL);

CREATE TABLE VEHICLE (
VehicleID INT IDENTITY(1,1) PRIMARY KEY,
LicensePlate VARCHAR(30) NOT NULL,
Model VARCHAR(50) NOT NULL,
Capacity INT NOT NULL,
Status VARCHAR(20) NOT NULL,
CONSTRAINT CK_Vehicle_Status CHECK (Status IN ('Available', 'Maintenance', 'Busy')));

CREATE TABLE [CREW_MEMBER] (
CrewMemberID INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Role VARCHAR(50) NOT NULL,
Phone VARCHAR(100) NOT NULL);

CREATE TABLE [PACKING_MATERIAL] (
MaterialID INT IDENTITY(1,1) PRIMARY KEY,
MaterialName VARCHAR(200) NOT NULL,
UnitPrice DECIMAL(10,2) NOT NULL);

CREATE TABLE [GEOGRAPHIC_ZONE](
ZoneID INT IDENTITY(1,1) PRIMARY KEY,
ZoneName VARCHAR(100) NOT NULL,
BaseRate DECIMAL(10,2) NOT NULL
CONSTRAINT CK_BaseRate CHECK (BaseRate > 0));

CREATE TABLE LOCATION (
LocationID INT IDENTITY(1,1) PRIMARY KEY,
ZoneID INT NOT NULL,
SteetAddress VARCHAR(200) NOT NULL,
City VARCHAR(50) NOT NULL,
State CHAR(50) NOT NULL,
ZipCode VARCHAR(20) NOT NULL,
Floor INT,
HasElevator BIT NOT NULL,
Constraint FK_LOCATION FOREIGN KEY (ZoneID) REFERENCES GEOGRAPHIC_ZONE(ZoneID));

CREATE TABLE [ORDER] (
OrderID INT IDENTITY(1,1) PRIMARY KEY,
CustomerID INT NOT NULL,
OriginID INT NOT NULL,
DestID INT NOT NULL,
ConsultantID INT NOT NULL,
OrderDate DATE NOT NULL,
TotalVolume DECIMAL(10,2) NOT NULL,
CONSTRAINT CK_Positive_Volume CHECK (TotalVolume >= 0),
CONSTRAINT FK_Order_Customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
CONSTRAINT FK_Order_Origin FOREIGN KEY (OriginID) REFERENCES LOCATION(LocationID),
CONSTRAINT FK_Order_Dest FOREIGN KEY (DestID) REFERENCES LOCATION(LocationID),
CONSTRAINT FK_Order_Consultant FOREIGN KEY (ConsultantID) REFERENCES CONSULTANT(ConsultantID));

CREATE TABLE [ESTIMATE] (
EstimateID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
EstimatedCost DECIMAL(10,2) NOT NULL,
ExpirationDate DATE NOT NULL,
CONSTRAINT FK_Estimate_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID));

CREATE TABLE [INVOICE] (
InvoiceID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
FinalTotal DECIMAL(10,2) NOT NULL,
PaymentStatus VARCHAR(500) NOT NULL,
IssueDate DATE NOT NULL,
CONSTRAINT FK_Invoice_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID));

CREATE TABLE [INVENTORY_ITEM] (
ItemID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
Description VARCHAR(800) NOT NULL,
IsFragile BIT NOT NULL,
CONSTRAINT FK_Inventory_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID));

CREATE TABLE [MATERIAL_USAGE] (
UsageID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
MaterialID INT NOT NULL,
QuantityUsed INT NOT NULL,
CONSTRAINT FK_Usage_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID),
CONSTRAINT FK_Usage_Material FOREIGN KEY (MaterialID) REFERENCES [PACKING_MATERIAL] (MaterialID));

CREATE TABLE [VEHICLE_ASSIGN] (
AssignmentID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
VehicleID INT NOT NULL,
StartMileage INT NOT NULL,
EndMileage INT NOT NULL,
CONSTRAINT FK_Assign_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID),
CONSTRAINT FK_Assign_Vehicle FOREIGN KEY (VehicleID) REFERENCES [VEHICLE] (VehicleID));

CREATE TABLE [CREW_ASSIGN] (
CrewAssignID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT NOT NULL,
CrewMemberID INT NOT NULL,
HoursWorked DECIMAL(10,2) NOT NULL,
CONSTRAINT FK_CrewAssign_Order FOREIGN KEY (OrderID) REFERENCES [ORDER] (OrderID),
CONSTRAINT FK_CrewAssign_CrewMember FOREIGN KEY (CrewMemberID) REFERENCES [CREW_MEMBER] (CrewMemberID));